on:
  release:
    types: [created]
jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin, illumos]
        goarch: [amd64]
        include:  
          - goarch: arm64
            goos: darwin 
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.33
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        extra_files: README.md LICENSE.md
        project_path: ./cmd